config/routes.rb
Apply::Application.routes.draw do
  
  get 'logout' => 'application#logout'
  
  get 'calls' => 'calls#index'
  get 'calls/:id' => 'calls#edit', :as => :call
  put 'calls/:id' => 'calls#update'
  
  get 'review/:model' => 'review#index', :as => :review
  get 'review/:model/:app_id' => 'review#show_or_edit', :as => :review_app
  post 'review/:model/:app_id' => 'review#create_or_update'
  get 'review/:model/:app_id/download/:column' => 'review#download', :as => :download
  
  get 'export/:model' => 'export#index', :as => :export
  
  get 'visualize/:model/:action' => 'visualize', :as => :visualize
  
  root :to => 'apply#new'
  get ':model' => 'apply#new', :as => :apply
  post ':model' => 'apply#create'
  
end

app/controllers/review_controller.rb
# Handles application reviews.
class ReviewController < ApplicationController
  
  before_filter :authenticate
  before_filter :call
  
  # List of submitted applications.
  def index
    @apps = @call.app_class.all(:select => @call.identity_columns_a << :id)
    if @call.reviewable
      srand @current_user.bytes.reduce(0x100, :^)
      @apps = @apps.sort_by { rand }
    end
    @reviews = @call.review_class.where(:app_reviewer_id => @current_user) if @call.review_class
  end
  
  # Show an application, with review form if reviewable.
  def show_or_edit
    @app = @call.app_class.find(params[:app_id])
    if @call.reviewable
      # Reviews are open
      @review = @call.review_class.find_or_initialize_by_app_reviewer_id_and_app_id(@current_user, @app.id)
      render :edit
    elsif @call.review_class
      # Reviews are closed
      @review = @call.review_class.find_by_app_reviewer_id_and_app_id(@current_user, @app.id)
      @summary = @call.review_class.summarize(@app)
      render :show
    else
      # No reviewing
      render :show
    end
  end
  
  # Create or update the user's review of the application.
  def create_or_update
    @app = @call.app_class.find(params[:app_id])
    if not @call.reviewable
      render :call_noreview and return
    end
    
    @review = @call.review_class.find_or_initialize_by_app_reviewer_id_and_app_id(@current_user, @app.id)
    @review.attributes = params[:review]
    
    if @review.save
      redirect_to review_path
    else
      render :edit
    end
  end
  
  # Download a file uploaded with an application.
  def download
    @app = @call.app_class.find(params[:app_id])
    column = params[:column].to_sym
    if @call.app_class.attachment_definitions? and @call.app_class.attachment_definitions[column]
      redirect_to @app.attachment_for(column).expiring_url
    else
      render :download_bad, :status => 404
    end
  end
  
end

app/helpers/review_helper.rb
module ReviewHelper
  
  def app_response(app, col)
    content = app[col.name]
    return nil if content == nil or content == ''
    
    case col.field_type
    when :date
      if col.name.ends_with? '_year'
        return app[col.name].year
      else
        return app[col.name]
      end
      
    when :text
      return simple_format app[col.name]
      
    when :boolean
      return app[col.name] ? 'yes' : 'no'
      
    when :paperclip
      return link_to 'download', download_path(:app_id => app.id, :column => col.field_name)
      
    else
      return app[col.name]
      
    end
  end
  
  def app_summary_response(call, app, col)
    content = app[col.name]
    return nil if content == nil or content == ''
    
    case col.field_type
    when :text
      return link_to_function('&para;'.html_safe) do |page|
        page.call('summary_reveal', page.literal('event'),
                                    call.identify(app),
                                    app.class.human_attribute_name(col.name),
                                    app_response(app, col))
      end
      
    when :paperclip
      return link_to '&darr;'.html_safe, download_path(:app_id => app.id, :column => col.field_name)
      
    else
      return app_response(app, col)
      
    end
  end
  
  # Returns a form tag (input, radio buttons, etc.) for the given column.
  def review_input(call, name, col)
    case col.type
    when :integer
      # Numeric scale
      options = call.review_class.column_options(col)
      content_tag(:table,
        content_tag(:tr,
          options.map { |v| content_tag(:td, radio_button(name, col.name, v == '?' ? '' : v)) } .join.html_safe
        ) + content_tag(:tr,
          options.map { |v| content_tag(:td, v) } .join.html_safe
        )
      )
      
    when :text
      # Long answer text
      '<br/>'.html_safe + text_area(name, col.name, :size => '25x4')
      
    when :boolean
      # Checkbox
      check_box(name, col.name)
      
    end
  end
  
  def review_output(review, col)
    case col.type
    when :boolean
      review[col.name] ? 'yes' : 'no'
      
    when :text
      '<br/>'.html_safe + review[col.name]
      
    else
      review[col.name]
      
    end
  end
  
  def review_summary_output(call, summary, col)
    return nil if summary == nil
    content = summary[col.name]
    return nil if content == nil or content == {}
    
    case col.type
    when :integer
      sprintf("%.1f", content).sub(/\.?0+$/,'')
      
    when :boolean
      sprintf("%.0f", content*100)
      
    else
      return link_to_function('&para;'.html_safe) do |page|
        page.call('summary_reveal', page.literal('event'),
                                    call.identify(summary.app),
                                    call.review_class.human_attribute_name(col.name).pluralize,
                                    review_summary_full_output(summary, col))
      end
      
    end
  end
  
  def review_summary_full_output(summary, col)
    return nil if summary == nil
    content = summary[col.name]
    return nil if content == nil
    
    content.keys.sort.map do |username|
      content_tag(:p,
        content_tag(:b, username) + ': ' + content[username])
    end .join.html_safe
  end
  
end

app/views/review/_app.html.erb
<div id="application">
  
<h1><%= @call.identify(@app) %></h1>

<% @call.app_class.form_columns.each do |c| %>
  <% next if @call.identity_columns_a.include? c.name %>
  <div class="app-block-<%= c.field_type %>">
  <h3><%= @call.app_class.human_attribute_name(c.name) %></h3>
  <p><%= app_response(@app, c) || '&mdash;'.html_safe %></p>
  </div>
<% end %>

</div>

app/views/review/_form.html.erb
<%= form_for :review, :url => review_app_path, :html => { :id => 'review' } do |f| %>
  
  <% if @review.errors.any? %>
    <div id="review-form-errors">
    <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
  <% end %>
  
  <% @call.review_class.form_columns.each do |c| %>
    <div>
    <%= f.label c.name %>
    <%= review_input @call, :review, c %>
    </div>
  <% end %>
  
  <div><%= f.submit 'Save' %></div>
  
<% end %>

app/views/review/_review.html.erb
<div id="review">

<h2>Your Review</h2>

<% @call.review_class.form_columns.each do |c| %>
  <div>
  <%= @call.review_class.human_attribute_name(c.name) %>
  <%= review_output @review, c %>
  </div>
<% end %>

</div>

app/views/review/_summary.html.erb
<div class="app-summary">

<h2>Review Summary</h2>

<% rest_cols = @call.review_class.form_columns %>

<% number_cols, rest_cols = rest_cols.partition { |c| c.type == :integer } %>
<table><tr>
<% number_cols.each { |c| %><td><%= @call.review_class.human_attribute_name(c.name) %></td><% } %>
</tr><tr>
<% number_cols.each { |c| %><td>
  <%= review_summary_output(@call, @summary, c) || '&mdash;'.html_safe %>
  <small>/ <%= @call.review_class.column_options(c).map { |o| o.to_i } .max %></small></td><% } %>
</tr></table>

<% boolean_cols, rest_cols = rest_cols.partition { |c| c.type == :boolean } %>
<table><tr>
<% boolean_cols.each { |c| %><td><%= @call.review_class.human_attribute_name(c.name) %></td><% } %>
</tr><tr>
<% boolean_cols.each { |c| %><td>
  <%= review_summary_output(@call, @summary, c) || '&mdash;'.html_safe %><small>%</small></td><% } %>
</tr></table>

<% rest_cols.each do |c| %>
  <h3><%= @call.review_class.human_attribute_name(c.name).pluralize %></h3>
  <%= review_summary_full_output(@summary, c) %>
<% end %>

</div>

app/views/review/call_bad.html.erb
<h1>Review Applications</h1>
<p>There are no "<%= params[:model].titleize %>" applications.</p>
<p>Please check the URL.</p>

app/views/review/call_noreview.html.erb
<h1><%= @call.app_class.model_name.human.titleize %> Applications</h1>
<p><%= @call.app_class.model_name.human.titleize %> application reviews are closed.</p>

app/views/review/download_bad.html.erb
<h1>Download <%= @call.app_class.model_name.human.titleize %> Attachment</h1>
<p><%= @call.app_class.model_name.human.titleize %> applications do not have a &ldquo;<%= params[:column] %>&rdquo; attachment.</p>
<p>Please check the URL.</p>

app/views/review/edit.html.erb
<% content_for :title do %>
<%= @call.app_class.model_name.human.titleize %> Application - <%= @call.identify(@app) %>
<% end %>

<% content_for :head do %>
<%= stylesheet_link_tag 'print', :media => 'print' %>
<% end %>

<%= render :partial => 'app' %>

<%= render :partial => 'form' %>

app/views/review/index.html.erb
<% content_for :title do %>
<%= @call.app_class.model_name.human.titleize %> Applications
<% end %>

<h1><%= @call.app_class.model_name.human.titleize %> Applications</h1>

<p>
<%= pluralize @apps.size, 'application' %> - 
<%= link_to 'export to csv', export_path(:format => :csv) %>
</p>
<% if @reviews %>
  <% done = @reviews.find_all { |r| r.complete? } %>
  <p>You have reviewed <%= done.size == @apps.size ? 'all' : done.empty? ? 'none' : done.size %> of them</p>
<% end %>
<% if @call.review_class and not @call.reviewable %>
  <p>
  <%= pluralize @call.review_class.count, 'review' %> total -
  <%= link_to 'table', visualize_path(:action => :table) %> -
  <%= link_to 'scatter', visualize_path(:action => :scatter) %> -
  <%= link_to 'splom', visualize_path(:action => :splom) %>
  </p>
<% end %>

<table>
<% @apps.each do |app| %>
  <tr>
    <% if review = @reviews && @reviews.find { |r| r.app_id == app.id } %>
      <% if review.complete? %>
        <td style="color:#9d9" title="Review complete">&#x2713;</td>
      <% else %>
        <td style="color:#933" title="Review incomplete">&mdash;</td>
      <% end %>
    <% else %>
      <% if @call.reviewable %>
        <td title="Needs review">&rarr;</td>
      <% else %>
        <td>&nbsp;</td>
      <% end %>
    <% end %>
    <td><%= link_to @call.identify(app), review_app_path(:app_id => app) %></td>
  </tr>
<% end %>
</table>

app/views/review/show.html.erb
<% content_for :title do %>
<%= @call.app_class.model_name.human.titleize %> Application - <%= @call.identify(@app) %>
<% end %>

<% content_for :head do %>
<%= stylesheet_link_tag 'print', :media => 'print' %>
<% end %>

<%= render :partial => 'app' %>

<% if @review %>
<%= render :partial => 'review' %>
<% end %>

<% if @summary %>
<br/>
<%= render :partial => 'summary' %>
<% end %>