config/routes.rb
Apply::Application.routes.draw do
  
  get 'logout' => 'application#logout'
  
  get 'calls' => 'calls#index'
  get 'calls/:id' => 'calls#edit', :as => :call
  put 'calls/:id' => 'calls#update'
  
  get 'review/:model' => 'review#index', :as => :review
  get 'review/:model/:app_id' => 'review#show_or_edit', :as => :review_app
  post 'review/:model/:app_id' => 'review#create_or_update'
  get 'review/:model/:app_id/download/:column' => 'review#download', :as => :download
  
  get 'export/:model' => 'export#index', :as => :export
  
  get 'visualize/:model/:action' => 'visualize', :as => :visualize
  
  root :to => 'apply#new'
  get ':model' => 'apply#new', :as => :apply
  post ':model' => 'apply#create'
  
end

app/models/call.rb
# A call for applications.
class Call < ActiveRecord::Base
  
  validates_format_of :id, :with => /\A[a-z]+\Z/
  
  # The ActiveRecord model application class for this call.
  def app_class
    Kernel.const_get(id.titleize)
  end
  
  # The ActiveRecord model review class for this call, if any.
  def review_class
    begin
      Kernel.const_get("#{id.titleize}Review")
    rescue NameError
      nil
    end
  end 
  
  # Identifying columns for the app (not necessarily uniquely).
  def identity_columns_a
    (identity_columns || app_class.content_columns.first.name).split
  end
  
  # Identifying string for the app (not necessarily unique).
  def identify(app, joiner = ' ')
    identity_columns_a.map { |c| app[c] } .join(joiner)
  end
  
end

app/controllers/calls_controller.rb
# Listing and editing calls for applications.
class CallsController < ApplicationController
  
  before_filter :authenticate
  
  # List of calls for applications.
  def index
    @calls = Call.all
  end
  
  # Form for editing a call.
  def edit
    @call = Call.find(params[:id])
  end
  
  # Update a call.
  def update
    @call = Call.find(params[:id])
    
    respond_to do |format|
      if @call.update_attributes(params[:call])
        format.html { redirect_to call_path }
      else
        format.html { render :action => :edit }
      end
    end
  end
  
end

app/helpers/call_helper.rb
module CallHelper
  
  # Returns an open/closed status div.
  def openclose(text, open)
    if open
      content_tag(:div, "#{text} open", :class => 'openclose-is-open')
    else
      content_tag(:div, "#{text} closed", :class => 'openclose-is-close')
    end
  end
  
end

app/views/calls/edit.html.erb
<% content_for :head do %>
<style>
form { width: 30%; }
iframe {
  position: absolute;
  top: 0;
  right: 0;
  height: 99%;
  width: 70%;
  border: none;
  border-left: 1px solid gray;
}
</style>
<% end %>

<%= form_for @call do |f| %>
  <h2><%= @call.id.titleize %> Application</h2>
  
  <p><%= f.label :title %><br/>
     <%= f.text_field :title, :size => 50 %></p>
  <p><%= f.label :deadline %><br/>
     <%= f.date_select :deadline, :start_year => Time.now.year,
                                  :end_year => Time.now.year + 1,
                                  :include_blank => true %> midnight</p>
  <p><%= f.label :description %><br/><small>also appears on app closed page</small><br/>
     <%= f.text_area :description, :size => '40x3' %></p>
  <p>Applications <%= f.check_box :open, :class => :openclose %></p>
  <p>
  <% if @call.review_class %>
    Reviews <%= f.check_box :reviewable, :class => :openclose %>
  <% else %>
    No reviewing
  <% end %>
  </p>
  
  <div style="text-align:center"><%= f.submit 'Update' %></div>
  
  <p><%= link_to '&larr; Back to list'.html_safe, calls_path %></p>
<% end %>

<iframe src="<%= apply_path(@call.id, :preview => true) %>">

app/views/calls/index.html.erb
<% content_for :head do %>
<style>
th {
  padding-right: 1em;
}
</style>
<% end %>

<h1>Calls for Applications</h1>

<table>
<tr><th></th><th colspan="2">Applications</th><th colspan="2">Reviews</th></tr>
<% @calls.sort_by { |c| c.app_class.model_name } .each do |call| %>
  <tr><th><%= link_to call.app_class.model_name.human.titleize.pluralize, call_path(call) %></th>
      <td><%= call.app_class.count %></td>
      <td><%= link_to openclose('', call.open), public_apply_url(:model => call.id) %></td>
      <td><%= call.review_class ? call.review_class.count : '-' %></td>
      <td><%= link_to openclose('', call.reviewable), review_path(:model => call.id) %></td></tr>
<% end %>
</table>